# Generated by Django 3.2.8 on 2021-11-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline',
        ),
        migrations.AddField(
            model_name='story',
            name='details',
            field=models.CharField(default='vgbhnj', max_length=500),
            preserve_default=False,
        ),
    ]
