# Generated by Django 3.2.8 on 2021-11-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211101_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(),
        ),
    ]
