# Generated by Django 3.2.8 on 2021-11-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211102_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='istoday',
        ),
        migrations.AddField(
            model_name='story',
            name='country',
            field=models.CharField(default='fgyhj', help_text='Country where the story is coming from', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(help_text='Eg: Sports, Entertainment', on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
