# Generated by Django 3.2.8 on 2021-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_story_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='country',
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
