# Generated by Django 3.2.8 on 2021-10-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='description',
        ),
        migrations.AddField(
            model_name='crime',
            name='report',
            field=models.TextField(default='rt', help_text='Eye witness report'),
            preserve_default=False,
        ),
    ]
